### ISSUE TITLE
Old version cmake build fails 

### ISSUE THREAD

**Issue by reoxey** [venediktov/vanilla-rtb#42]
reference #40 
I tried building the project in cmake 3.2.2 but gives errors like
- cannot run .c
- threads not found
but when i upgraded to cmake 3.8.2, the build was successfull
so right now i'm using gcc - 7.1.0 & boost - 1.61

it will better to provide the least version of cmake supported, for those who are new to this repo.

Regards.

**Comment by mrbald** [comment]
@reoxey - many thanks for root causing it, I'll update the top level CMakeLists.txt with correct minimum version spec.
