### ISSUE TITLE
upgrade compiler to C++17

### ISSUE THREAD

**Issue by venediktov** [venediktov/vanilla-rtb#82]
- see if travis can handle C++17 either gcc 7.1 or clang 5.0 
- move our C++17 implementation of **audit_buffer.hpp** , **audit_codec.hpp** into official build
- change code as needed to compile on **gcc >= 7.1** and on **clang >= 5.0**
- update README.md

**Comment by venediktov** [comment]
@mrbald well done!

**Comment by mrbald** [comment]
all done, source code syntax changes kept to the minimum - only things that did not compile were fixed, further improvements are better to be done as separate focused changes.

it was fun :-)
